### ISSUE TITLE
WYSIWYG editor is not showing up for me.

### ISSUE THREAD

**Issue by apmitchell** [Gottwik/enduro_quill#1]
Not sure what I'm doing wrong.
I have re-installed enduro to get the latest as well as re-installing this package.

```sh
enduro --version
1.4.44
```

Here are a few screenshots of my setup, let me know if anything is jumping out to you or if you have any suggestions on what I may be doing wrong.  Much appreciated.

<img width="480" alt="screen shot 2018-01-07 at 10 17 22 pm" src="https://user-images.githubusercontent.com/5396521/34660665-dfb019bc-f3f8-11e7-86bd-4023cd3f0f31.png">
<img width="249" alt="screen shot 2018-01-07 at 10 16 26 pm" src="https://user-images.githubusercontent.com/5396521/34660666-dfc6faf6-f3f8-11e7-9d26-be85cbf0030e.png">
<img width="289" alt="screen shot 2018-01-07 at 10 16 09 pm" src="https://user-images.githubusercontent.com/5396521/34660667-dfde3874-f3f8-11e7-9177-d144c88ec59d.png">
<img width="420" alt="screen shot 2018-01-07 at 10 16 01 pm" src="https://user-images.githubusercontent.com/5396521/34660668-dff6d00a-f3f8-11e7-9356-d1b814e22fff.png">
<img width="1888" alt="screen shot 2018-01-07 at 10 15 35 pm" src="https://user-images.githubusercontent.com/5396521/34660669-e00e3cea-f3f8-11e7-925f-bf37113702ea.png">

**Comment by dtaburetkin** [comment]
do not use $company_name_type name for admin-commands and variables names... algorhitm "terminator_tools" little bit dumb. Here he will return 'name_type', but must return 'type'.
use $companyname_type and companyname:
i fell into the same trap.

**Comment by apmitchell** [comment]
Appreciate the insight! Thanks @dtaburetkin.

**Comment by akimo** [comment]
@workaround until fixed #2
