### ISSUE TITLE
The toolbar wont show

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [Gottwik/enduro_quill#2]
ver: 1.4.45

See related (I dont have any names problem)
https://github.com/Gottwik/enduro_quill/issues/1

```
	$test_type: 'quill',
	test: '',
```
Why this is happen? (I do the same steps on 1.4.42) and this works fine.

![image](https://user-images.githubusercontent.com/16711871/35196992-4b626590-fee2-11e7-9057-7868ea369603.png)

**Comment by guardabrazo** [comment]
Same problem here.
enduro@1.4.45
enduro_quill@1.0.6

<img width="609" alt="captura de pantalla 2018-01-21 a las 19 03 50" src="https://user-images.githubusercontent.com/5084831/35197332-ed117bba-fedd-11e7-8042-401b36966ce9.png">

<img width="670" alt="captura de pantalla 2018-01-21 a las 18 54 08" src="https://user-images.githubusercontent.com/5084831/35197305-8df565b0-fedd-11e7-85ee-139d4d22dc06.png">

**Comment by Ezra-Siton-UIX** [comment]
https://github.com/Gottwik/Enduro/issues/193

**Comment by guardabrazo** [comment]
@Ezra-Siton-UIX did you manage to solve this somehow?

**Comment by Ezra-Siton-UIX** [comment]
No.

**Comment by akimo** [comment]
The Editor is loaded - only the toolbar is empty. You can add the buttons/elems you want in the quill settings in file "enduro.json" of your website root. 

```
        ..
	"bricks": {
		"enduro_quill": {
			"modules": {
				"toolbar": [
					["bold", "italic", "underline", "strike"],
					["blockquote", "code-block"],

					[{ "header": 1 }, { "header": 2 }],
					[{ "list": "ordered"}, { "list": "bullet" }],
					[{ "script": "sub"}, { "script": "super" }],
					[{ "indent": "-1"}, { "indent": "+1" }],
					[{ "direction": "rtl" }],

					[{ "size": ["small", false, "large", "huge"] }],
					[{ "header": [1, 2, 3, 4, 5, 6, false] }],

					[{ "color": [] }, { "background": [] }],
					[{ "font": [] }],
					[{ "align": [] }],

					["clean"]
				]
			},
			"placeholder": "Compose an epic...",
			"theme": "snow"
		}
	}
```

I also updated the linked Quill JS Versions in "[local-website]/node_modules/enduro_quill/assets/inject_quill_to_admin.js" to current version "1.3.5" (JS+CSS). (temporary Hotfix until enduro_quill will be updated)

@see: 
=> https://quilljs.com/docs/modules/toolbar/
=> https://github.com/quilljs/quill/issues/1164

**Comment by Ezra-Siton-UIX** [comment]
> "I also updated the linked Quill JS Versions in "[local-website]/node_modules/enduro_quill/assets/inject_quill_to_admin.js" to current version "1.3.5" (JS+CSS). (temporary Hotfix until enduro_quill will be updated)"

@akimo  - please **Add more details about this step. Thanks** (I change the json but the toolbar still won't show).  

Won't work for me.

**Comment by akimo** [comment]
Ok, i've tested it again. The solution is much more simple:
All you have to do is to configure the "theme" for the Quill-Brick in "enduro.json" of your website root.

Mine looks like this:

```
{
	"project_name": "test",
	"project_slug": "quill toolbar test",
	"bricks": {
		"enduro_quill": {
			"theme": "snow"
		}
	}
}

```

Its not necessary to update the quill css & js links to current quill version (mine is 1.3.3). To see the changes and the default toolbar you have to Restart the enduro server. 

My Versions
- Node v9.5.0
- enduro 1.4.46
- enduro_quill 1.0.6




```

**Comment by Ezra-Siton-UIX** [comment]
@akimo - Thanks now the toolbar is `showing`. Anyway, I hope some update will fix this issue for all users. 

## Restart 
For other users: After editing the toolbar -  **Restart enduro** - exit (`ctr + c` and `ctr + c`) - than run (`enduro dev`) - to see the changes in the admin (In other words - not by F5 "refresh")

## Solution - "Edit the toolbar"
Edit the toolbar under this codepen (change order, group buttons and add/remove options) - than copy-paste the `array `option to enduro.json:
https://codepen.io/ezra_siton/pen/VQVEwK

Example (of `enduro.json` with quill & Custom toolbar )

```
{
	"project_name": "enduro_intro",
	"project_slug": "ei",
	"cultures": [
		"de",
		"en"
	],
       /* quill rich text editor */
	"bricks": {
		"enduro_quill": {
			"toolbar": [
					["bold", "italic", "underline", "strike"],
					["blockquote", "code-block"],

					[{ "header": 1 }, { "header": 2 }],
					[{ "list": "ordered"}, { "list": "bullet" }],
					[{ "script": "sub"}, { "script": "super" }],
					[{ "indent": "-1"}, { "indent": "+1" }],
					[{ "direction": "rtl" }],

					[{ "link": [] }],
					[{ "size": ["small", false, "large", "huge"] }],
					[{ "header": [1, 2, 3, 4, 5, 6, false] }],

					[{ "color": [] }, { "background": [] }],
					[{ "font": [] }],
					[{ "align": [] }],

					["clean"]
				],

			"theme": "snow"
		}
	}
}

```
## quill.js toolbar DOCS
https://quilljs.com/docs/modules/toolbar/

**related topic (how to add quill to enduro):**
https://github.com/Gottwik/Enduro/issues/158
